### ISSUE TITLE
Preparing training and testing sets

### ISSUE THREAD

**Issue by versae** [douglasbagnall/caravel#1]
First of all, thanks for sharing this code of the PAN15 competition.

Second, how should I prepare my own dataset and then train `caravel` to find the author of my anonymous text?

**Comment by douglasbagnall** [comment]
Unfortunately it isn't set up to find the author of arbitrary texts, just to win the PAN competition.

The place to start is `./pan-test --help`. You give pan-test an input directory in the form that PAN2015 uses, as described [here](http://www.uni-weimar.de/medien/webis/events/pan-15/pan15-web/author-identification.html).

If you look at the pan-test source, you'll see it calls `train-net`, which you will see has lots of options. Possibly some combination of those options will get close to what you want.

**Comment by versae** [comment]
Thank you! I will definitively try that.
